import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile,readdir } from 'node:fs/promises';
import {defaultData} from '../src/pages/editor/data.js';
import {renderSite,safeUrl,PALETTES,FONT_CHOICES} from '../src/site.js';
import {validateData,REPOSITORY,App} from '../src/pages/editor/app.js';
const clone=()=>structuredClone(defaultData);
function render(d,mode='home'){const root={innerHTML:'',querySelector:()=>({addEventListener(){},getAttribute(){return 'false'},setAttribute(){},classList:{toggle(){},remove(){}}}),querySelectorAll:()=>[]};renderSite(root,d,mode);return root.innerHTML;}
test('build contains independent site, CMS and published content',async()=>{const files=await readdir('dist');for(const f of ['index.html','cms.html','connexion.html','cv-data.json'])assert.ok(files.includes(f));assert.equal(JSON.parse(await readFile('dist/cv-data.json','utf8')).version,2);assert.doesNotMatch(await readFile('dist/index.html','utf8'),/githubToken/);});
test('two locations include correct institutional links and phone calls',()=>{const html=render(clone());assert.match(html,/Sainte-Élisabeth/);assert.match(html,/La Ridale/);assert.match(html,/href="tel:\+3281720581"/);assert.match(html,/href="tel:\+3281208580"/);assert.match(html,/chuuclnamur.be/);assert.match(html,/centremedicaldelaridale.be/);assert.doesNotMatch(html,/cabinet.neurologie@example.com/);});
test('each location and contact can be added, hidden or removed',()=>{const d=clone();d.locations[0].visible=false;d.locations.push({...d.locations[1],name:'Centre de test',url:'https://example.com/centre'});d.contacts[0].visible=true;d.contactSection.visible=true;assert.doesNotMatch(render(d),/Sainte-Élisabeth/);assert.match(render(d),/Centre de test/);assert.match(render(d),/mailto:cabinet.neurologie@example.com/);d.locations=[];assert.doesNotMatch(render(d),/id="lieux"/);});
test('individual appointment, telephone and map links hide across public page',()=>{const d=clone();for(const l of d.locations){l.linkVisible=false;l.phoneVisible=false;l.mapVisible=false;l.bookingVisible=false;}const html=render(d);assert.doesNotMatch(html,/chuuclnamur.be|centremedicaldelaridale.be|tel:\+32|google.com\/maps/);assert.match(html,/Sainte-Élisabeth/);});
test('all content sections hide and associated anchors disappear',()=>{const d=clone();for(const key of ['hero','about','topics','locationsSection','practical','faqSection','contactSection','emergency','legal'])d[key].visible=false;const html=render(d);assert.doesNotMatch(html,/id="approche"|id="expertises"|id="lieux"|id="pratique"|id="contact"|href="#lieux"/);});
test('maintenance replaces all public content with custom text',()=>{const d=clone();d.maintenance={enabled:true,title:'Test construction',message:'Revenez demain.'};const html=render(d);assert.match(html,/Test construction/);assert.match(html,/Revenez demain/);assert.doesNotMatch(html,/La Ridale|site-header|id="lieux"|cabinet/);});
test('FAQ, preparation and conditions obey element visibility',()=>{const d=clone();d.conditions[0].visible=false;d.preparations[0].visible=false;d.faqs[0].visible=false;const html=render(d,'consult');assert.doesNotMatch(html,/Maux de tête &amp; migraines|Vos documents|Comment prendre rendez-vous/);});
test('content is escaped and unsafe protocols are rejected',()=>{const d=clone();d.general.name='<img src=x onerror=alert(1)>';d.locations[0].url='javascript:alert(1)';const html=render(d);assert.doesNotMatch(html,/<img src=x|href="javascript:/);assert.match(html,/&lt;img/);for(const u of ['javascript:alert(1)','data:text/html,test','ftp://example.com'])assert.equal(safeUrl(u),'');assert.ok(safeUrl('https://example.com'));});
test('JSON import validates schema and does not merge unknown properties',()=>{const d=clone();assert.deepEqual(validateData(d),d);d.extra='ignored';assert.equal(validateData(d).extra,undefined);d.locations[0].url='javascript:bad';assert.throws(()=>validateData(d),/Lien invalide/);assert.throws(()=>validateData({}),/version 2/);const invalid=clone();invalid.maintenance.enabled='false';assert.throws(()=>validateData(invalid),/Champ invalide/);});
test('CMS targets only the new repository and does not persist secrets',async()=>{assert.equal(REPOSITORY,'Optimist97/neurologue');const src=await readFile('src/pages/editor/app.js','utf8');assert.doesNotMatch(src,/cv-portfolio|localStorage\.setItem\([^\n]*token/i);assert.match(src,/remote.sha!==this.baseSha/);});


test('homepage presents doctor and preparation; consultation topics remain on their own page',()=>{const d=clone(),home=render(d),info=render(d,'consult');assert.match(home,/<h1>Dr Olivia Renard<\/h1>/);assert.match(home,/portrait.png/);assert.match(home,/consultations.html/);assert.doesNotMatch(home,/Prendre rendez-vous|id="expertises"/);assert.match(info,/id="expertises"/);assert.match(home,/Préparer votre consultation/);assert.doesNotMatch(info,/Préparer votre consultation/);assert.doesNotMatch(info,/class="hero wrap"|id="lieux"/);d.maintenance.enabled=true;assert.doesNotMatch(render(d,'consult'),/id="expertises"/);});
test('secondary page can be hidden independently',()=>{const d=clone();d.infoPage.visible=false;assert.doesNotMatch(render(d),/href=".\/consultations.html"/);assert.match(render(d,'consult'),/Page indisponible/);});
test('pastel choices retain readable contrast and are the only allowed backgrounds',()=>{function luminance(hex){const c=hex.match(/[a-f0-9]{2}/g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];}assert.equal(Object.keys(PALETTES).length,5);for(const p of Object.values(PALETTES)){for(const color of ['#183e37','#58675f'])assert.ok((luminance(p.paper)+.05)/(luminance(color)+.05)>=4.5);}const d=clone();d.general.background='terracotta';assert.equal(validateData(d).general.background,'terracotta');d.general.background='black';assert.throws(()=>validateData(d),/fonds pastels/);});
test('all three font choices apply alongside the selected palette',()=>{assert.equal(Object.keys(FONT_CHOICES).length,3);for(const key of Object.keys(FONT_CHOICES)){const d=clone();d.general.typography=key;d.general.background='terracotta';const properties={};const root={ownerDocument:{documentElement:{style:{setProperty:(key,value)=>properties[key]=value}}},querySelector:()=>({addEventListener(){}}),querySelectorAll:()=>[]};renderSite(root,d);assert.equal(properties['--serif'],FONT_CHOICES[key].serif);assert.equal(properties['--paper'],PALETTES.terracotta.paper);}const d=clone();d.general.typography='unknown';assert.throws(()=>validateData(d),/typographies/);});
test('publication sends UTF-8 content to the new repository and refuses stale writes',async()=>{const previousFetch=globalThis.fetch,previousDocument=globalThis.document;const button={disabled:false};globalThis.document={getElementById:()=>button};const instance=Object.create(App.prototype);instance.data=clone();instance.token='test-only';instance.baseSha='baseline';instance.remote=async()=>({sha:'baseline'});instance.save=()=>{};let status='',payload;instance.githubStatus=message=>status=message;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.github.com/repos/Optimist97/neurologue/contents/public/cv-data.json');assert.equal(options.method,'PUT');payload=JSON.parse(options.body);return {ok:true,json:async()=>({content:{sha:'updated'}})};};try{await instance.publish();assert.equal(instance.baseSha,'updated');assert.equal(payload.sha,'baseline');const data=JSON.parse(Buffer.from(payload.content,'base64').toString('utf8'));assert.deepEqual(data,instance.data);assert.match(status,/Contenu publié/);payload=null;instance.remote=async()=>({sha:'other'});await instance.publish();assert.equal(payload,null);assert.match(status,/autre modification/);}finally{globalThis.fetch=previousFetch;globalThis.document=previousDocument;}});
test('each consultation location has an editable ROSA booking button independent of institutional link',()=>{const d=clone();let html=render(d);assert.equal((html.match(/booking-link/g)||[]).length,2);assert.match(html,/registry.chuuclnamur.rosa.be\/fr\/search/);assert.match(html,/rosa.be\/fr\/org\/centre-de-la-ridale/);d.locations[0].bookingVisible=false;html=render(d);assert.equal((html.match(/booking-link/g)||[]).length,1);assert.match(html,/chuuclnamur.be\/services/);d.locations[1].bookingLabel='Réserver au centre';d.locations[1].bookingUrl='https://rosa.be/fr/test';html=render(d);assert.match(html,/Réserver au centre/);assert.match(html,/https:\/\/rosa.be\/fr\/test/);});
test('legacy drafts do not inherit an incorrect booking link and unsafe booking URLs are refused',()=>{const d=clone();for(const l of d.locations){delete l.bookingUrl;delete l.bookingVisible;delete l.bookingLabel;}const data=validateData(d);assert.ok(data.locations.every(l=>l.bookingUrl===''&&l.bookingVisible===false));d.locations[0].bookingUrl='javascript:bad';assert.throws(()=>validateData(d),/Lien invalide/);});
test('font sizes migrate old content and reject values outside readable limits',()=>{const d=clone();delete d.general.menuSize;delete d.general.titleSize;delete d.general.textSize;const migrated=validateData(d);assert.equal(migrated.general.menuSize,18);assert.equal(migrated.general.textSize,18);assert.equal(migrated.general.titleSize,40);for(const [key,value] of [['menuSize',15],['titleSize',100],['textSize',NaN],['textSize',18.5]]){const invalid=clone();invalid.general[key]=value;assert.throws(()=>validateData(invalid));}});
test('size settings are applied to both public pages and maintenance',()=>{for(const mode of ['home','consult']){const d=clone();Object.assign(d.general,{menuSize:24,titleSize:56,textSize:24});const css={};const root={ownerDocument:{documentElement:{style:{setProperty:(key,value)=>css[key]=value}}},querySelector:()=>({addEventListener(){}}),querySelectorAll:()=>[]};renderSite(root,d,mode);assert.equal(css['--menu-size'],'24px');assert.equal(css['--title-size'],'56px');assert.equal(css['--text-size'],'24px');d.maintenance.enabled=true;renderSite(root,d,mode);assert.equal(css['--text-size'],'24px');}});
test('both personal token types connect and load the current UTF-8 site without persisting tokens',async()=>{const oldFetch=globalThis.fetch,oldDocument=globalThis.document;try{for(const token of ['github_pat_testOnly','ghp_testOnly']){const elements={githubToken:{value:token},disconnect:{disabled:true},publish:{disabled:true}};globalThis.document={getElementById:id=>elements[id]};const instance=Object.create(App.prototype);Object.assign(instance,{hasDraft:false,dirty:false,baseSha:null,render(){},preview(){},githubStatus(message){this.message=message;}});const remote=clone();remote.general.name='Dr Élodie Renard';globalThis.fetch=async(url,options)=>{assert.equal(options.headers.Authorization,'Bearer '+token);return {ok:true,json:async()=>url.endsWith('/user')?{login:'Optimist97'}:{sha:'current',content:Buffer.from(JSON.stringify(remote)).toString('base64')}};};await instance.connect();assert.equal(elements.githubToken.value,'');assert.equal(elements.publish.disabled,false);assert.equal(instance.data.general.name,'Dr Élodie Renard');assert.equal(instance.baseSha,'current');instance.disconnect();assert.equal(instance.token,null);assert.equal(elements.publish.disabled,true);}}finally{globalThis.fetch=oldFetch;globalThis.document=oldDocument;}});
test('expired tokens do not enable publishing',async()=>{const oldFetch=globalThis.fetch,oldDocument=globalThis.document;const elements={githubToken:{value:'github_pat_testOnly'},publish:{disabled:true},disconnect:{disabled:true}};globalThis.document={getElementById:id=>elements[id]};globalThis.fetch=async()=>({ok:false,status:401});const instance=Object.create(App.prototype);instance.githubStatus=message=>instance.message=message;try{await instance.connect();assert.equal(instance.token,null);assert.equal(elements.publish.disabled,true);assert.match(instance.message,/expiré/);}finally{globalThis.fetch=oldFetch;globalThis.document=oldDocument;}});
test('write permissions errors explain the required repository permission and preserve the draft',async()=>{const oldFetch=globalThis.fetch,oldDocument=globalThis.document;globalThis.document={getElementById:()=>({disabled:false})};globalThis.fetch=async()=>({ok:false,status:403,json:async()=>({message:'Forbidden'})});const instance=Object.create(App.prototype);Object.assign(instance,{data:clone(),token:'test-only',baseSha:'current',remote:async()=>({sha:'current'}),githubStatus(message){this.message=message;},save(){throw new Error('Failed writes must not save');}});try{await instance.publish();assert.match(instance.message,/Contents : lecture et écriture/);assert.equal(instance.baseSha,'current');}finally{globalThis.fetch=oldFetch;globalThis.document=oldDocument;}});

test('dedicated login hides editor until connection and restores login on logout',()=>{const old=globalThis.document;const elements={loginView:{hidden:false},editorView:{hidden:true},save:{focus(){}},githubToken:{focus(){}}};globalThis.document={getElementById:id=>elements[id]};try{const app=Object.create(App.prototype);app.setSessionView(true);assert.equal(elements.loginView.hidden,true);assert.equal(elements.editorView.hidden,false);app.setSessionView(false);assert.equal(elements.loginView.hidden,false);assert.equal(elements.editorView.hidden,true);}finally{globalThis.document=old;}});
test('login field is empty and provides no credential hints',async()=>{const html=await readFile('src/connexion.html','utf8');assert.match(html,/id="editorView" hidden/);assert.doesNotMatch(html,/placeholder=|github_pat_|ghp_|Only select repositories|Contents →/);});

test('each neurology illustration can be hidden independently from the CMS',()=>{const d=clone();assert.match(render(d),/neuro-brain/);assert.match(render(d),/neuro-rhythm/);assert.match(render(d,'consult'),/neuro-neurons/);d.about.illustrationVisible=false;d.infoPage.illustrationVisible=false;d.practical.illustrationVisible=false;assert.doesNotMatch(render(d),/neuro-brain|neuro-rhythm/);assert.doesNotMatch(render(d,'consult'),/neuro-neurons/);});

test('CMS separates home, consultation and shared fields without changing content',()=>{const old=globalThis.document,fields={innerHTML:''},context={textContent:''};globalThis.document={querySelectorAll:()=>[],getElementById:id=>id==='fields'?fields:context};const app=Object.create(App.prototype);app.data=clone();try{app.editorPage='home';app.render();assert.match(fields.innerHTML,/data-section="practical"/);assert.doesNotMatch(fields.innerHTML,/data-section="conditions"|data-section="general"/);app.editorPage='consult';app.render();assert.match(fields.innerHTML,/data-section="conditions"/);assert.doesNotMatch(fields.innerHTML,/data-section="practical"|data-section="locations"/);app.editorPage='shared';app.render();assert.match(fields.innerHTML,/data-section="general"/);assert.doesNotMatch(fields.innerHTML,/data-section="conditions"/);assert.deepEqual(app.data,clone());}finally{globalThis.document=old;}});

test('both pages share the full menu with valid cross-page anchors and visibility controls',()=>{const d=clone();const nav=mode=>render(d,mode).match(/<nav[^>]*>([\s\S]*?)<\/nav>/)[1];const labels=html=>[...html.matchAll(/<a[^>]*>(.*?)<\/a>/g)].map(m=>m[1]);assert.deepEqual(labels(nav('home')),labels(nav('consult')));for(const anchor of ['approche','lieux','pratique'])assert.match(nav('consult'),new RegExp('href="\\./index.html#'+anchor+'"'));assert.match(nav('consult'),/aria-current="page"/);assert.doesNotMatch(nav('consult'),/href="#pratique"/);d.about.visible=false;d.locationsSection.visible=false;d.practical.visible=false;for(const page of ['home','consult'])assert.doesNotMatch(nav(page),/Présentation|Préparer la consultation|>Consultations</);});
